import { useEffect, useMemo, useRef, useState } from 'react';

import { Chip } from '../components/Panel.jsx';
import { ConfirmButton } from '../components/ConfirmButton.jsx';
import {
  EFFECT_NOTES,
  PROVENANCE_LABELS,
  PROVENANCE_LEVELS,
  SUPPLIED_NOTES,
  daysOld,
  fetchSetup,
  fieldsByTier,
  gateDecision,
  isAnswered,
  outstandingIds,
  setDate,
  staleById,
} from '../lib/setup.js';

/**
 * The setup page.
 *
 * Not a wizard. The argument for that is in `docs/setup_page.md` and it comes
 * down to this: somebody arriving on a beach with nothing filled in needs to
 * see *the whole list, ranked*, so they can decide what to do with the
 * daylight they have. A wizard hides the list behind a sequence, which is
 * fine the first time and obstructive every time after — and after the first
 * deployment every visit here is to change one value.
 *
 * So the page **is** the checklist. Three things carry that:
 *
 * 1. **The headline**, generated by `asket_common/setup_profile.py` and not
 *    assembled here, so the page, the pre-flight and anything else rank the
 *    work identically. It separates "there is no sensible default for this"
 *    from "this is on a guess that can ruin a survey quietly" from "this is
 *    an unchecked default that only makes the screen worse", because those are
 *    three different jobs and the first all-amber pre-flight proved that an
 *    undifferentiated list gets ignored.
 *
 * 2. **The consequence beside every field.** "Sonar lever arm, forward of
 *    GNSS" tells somebody what to type and nothing about whether it is worth
 *    getting off the pontoon with a tape measure. The sentence that says what
 *    a wrong value does is the reason a value gets measured rather than
 *    guessed, and it is why `measured:` has sat false for two weeks while the
 *    pre-flight named a YAML file nobody could open.
 *
 * 3. **Two tiers, because they encode the expected lifetime of a value.**
 *    Vessel values are how the boat is built: measured once, properly, and
 *    they never go stale. Deployment values are where you are today, and the
 *    page says how old each one is. Mounting geometry measured in July is
 *    still true in September; a station position from July is a different
 *    beach.
 *
 * What this page never does is claim a change has taken effect because a file
 * was written. Saving and applying are separate, and the page says which has
 * happened — see `pending_effects` in the Python and the save panel below.
 */

/** Read the field a deep link asked for: `#setup/vessel.sonar.side`. */
function hashField() {
  const hash = typeof window === 'undefined' ? '' : window.location.hash;
  const match = /^#setup\/(.+)$/.exec(hash || '');
  return match ? decodeURIComponent(match[1]) : '';
}

export function SetupPage({ state, connection, onClose }) {
  const [doc, setDoc] = useState(null);
  const [error, setError] = useState('');
  const [edits, setEdits] = useState({});
  const [focusField, setFocusField] = useState(hashField);
  const focusRef = useRef(null);

  // The document is fetched rather than streamed. Setup is needed most when
  // the link is worst, and a page the `minimal` profile could negotiate away
  // would vanish exactly when somebody is working out why it is minimal.
  useEffect(() => {
    let live = true;
    fetchSetup(connection)
      .then((next) => { if (live) { setDoc(next); setError(''); } })
      .catch((err) => { if (live) setError(String(err && err.message ? err.message : err)); });
    return () => { live = false; };
  }, [connection]);

  useEffect(() => {
    const onHash = () => setFocusField(hashField());
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, []);

  // Scroll a deep-linked field into view once, after the document arrives.
  // This is the other half of the pre-flight naming a field instead of a YAML
  // path: the name has to land somewhere.
  useEffect(() => {
    if (doc && focusField && focusRef.current) {
      focusRef.current.scrollIntoView({ block: 'center' });
    }
  }, [doc, focusField]);

  const gate = useMemo(() => gateDecision(state), [state]);
  const byTier = useMemo(() => fieldsByTier(doc), [doc]);
  const outstanding = useMemo(() => outstandingIds(doc), [doc]);
  const stale = useMemo(() => staleById(doc), [doc]);
  const dirty = Object.keys(edits);

  if (error) {
    return (
      <div className="setup-page">
        <SetupHeader onClose={onClose} />
        <p className="errline">
          The setup could not be read: {error}. Nothing has been changed.
        </p>
      </div>
    );
  }

  if (!doc) {
    return (
      <div className="setup-page">
        <SetupHeader onClose={onClose} />
        <p className="hint">Reading the setup…</p>
      </div>
    );
  }

  return (
    <div className="setup-page">
      <SetupHeader onClose={onClose} />

      {/* The scroller, so the save bar below is a sibling rather than a
          sticky child of it. A sticky bar whose height changes with the
          number of unsaved edits cannot be cleared by a fixed padding, and
          what it covers at full scroll is the last field on the page. */}
      <div className="setup-scroll">

      {/* Generated in Python. See the comment at the top of this file. */}
      <p className="setup-headline">{doc.headline}</p>

      <SetupFileNote doc={doc} />

      {doc.unknown_fields.length > 0 && (
        <div className="setup-unknown errline">
          <strong>
            {doc.unknown_fields.length === 1
              ? 'The setup file holds one entry this vessel does not recognise:'
              : `The setup file holds ${doc.unknown_fields.length} entries this `
                + 'vessel does not recognise:'}
          </strong>
          <ul>{doc.unknown_fields.map((id) => <li key={id}><code>{id}</code></li>)}</ul>
          {/* Almost always a typo in a value somebody did measure. Shown
              rather than dropped, because dropping it silently means the
              measurement never reaches the vessel and nobody finds out. */}
          <p>
            These are being ignored. A misspelt field is usually a value
            somebody did measure, so it is worth checking against the names
            below before assuming it is junk.
          </p>
        </div>
      )}

      {doc.tiers.map((tier) => (
        <section className="setup-tier" key={tier.id}>
          <h2>
            {tier.label}
            <TierChip
              fields={byTier.get(tier.id) ?? []}
              outstanding={outstanding}
              stale={stale}
            />
          </h2>
          <p className="hint setup-tier-blurb">{tier.blurb}</p>
          <div className="setup-fields">
            {(byTier.get(tier.id) ?? []).map((spec) => (
              <SetupField
                key={spec.id}
                spec={spec}
                entry={doc.values[spec.id] ?? null}
                effective={doc.effective[spec.id]}
                outstanding={outstanding.has(spec.id)}
                stale={stale.get(spec.id) ?? null}
                edit={edits[spec.id]}
                onEdit={(value) => setEdits((prev) => ({ ...prev, [spec.id]: value }))}
                onRevert={() => setEdits((prev) => {
                  const next = { ...prev };
                  delete next[spec.id];
                  return next;
                })}
                focused={focusField === spec.id}
                focusRef={focusField === spec.id ? focusRef : null}
              />
            ))}
          </div>
        </section>
      ))}

      </div>

      <SetupSaveBar
        dirty={dirty}
        edits={edits}
        doc={doc}
        gate={gate}
        state={state}
        connection={connection}
        onDiscard={() => setEdits({})}
        onSaved={() => {
          setEdits({});
          // Re-read rather than patch the document in place. The vessel is
          // the authority on what it now holds, and a page that updated its
          // own copy would be showing a local echo of a save — the same
          // mistake as a mode button that goes green on being pressed.
          fetchSetup(connection).then(setDoc).catch(() => {});
        }}
      />
    </div>
  );
}

function SetupHeader({ onClose }) {
  return (
    <header className="setup-topbar">
      <h1>Setup</h1>
      <div className="spacer" />
      <button type="button" onClick={onClose}>Back to the cockpit</button>
    </header>
  );
}

/**
 * What is true of a tier right now, not what the tier is.
 *
 * The blurb below already says what Vessel and Deployment mean, and it comes
 * from the Python so there is one description rather than two. This says how
 * much of the tier is outstanding — which is the thing that changes, and the
 * only thing worth spending amber on. Amber means "needs attention"
 * everywhere else in this GUI, and using it as a category label is how it
 * stops meaning that.
 */
function TierChip({ fields, outstanding, stale }) {
  const unanswered = fields.filter((spec) => outstanding.has(spec.id)).length;
  const old = fields.filter((spec) => stale.has(spec.id)).length;

  if (unanswered === 0 && old === 0) {
    return <Chip level="ok">All {fields.length} answered</Chip>;
  }
  const parts = [];
  if (unanswered) parts.push(`${unanswered} of ${fields.length} not set`);
  if (old) parts.push(`${old} worth re-checking`);
  return <Chip level="warn">{parts.join(', ')}</Chip>;
}

export function SetupFileNote({ doc }) {
  const file = doc.file || {};
  if (file.error) {
    return (
      <p className="errline">
        <strong>The setup file will not parse.</strong> {file.error} The values
        below are this vessel&rsquo;s shipped defaults — none of the answers in
        that file are in use. The file is at <code>{file.path}</code>.
      </p>
    );
  }
  if (file.missing) {
    return (
      <p className="warnline">
        Nothing has been saved on this vessel yet. The file will be created at{' '}
        <code>{file.path}</code> the first time something is saved.
      </p>
    );
  }
  if (doc.written_utc_ms) {
    return (
      <p className="hint">
        Last saved {setDate(doc.written_utc_ms)}
        {doc.written_by ? ` by ${doc.written_by}` : ''} ({daysOld(
          doc.server_utc_ms - doc.written_utc_ms,
        )}).
      </p>
    );
  }
  return null;
}

/**
 * One field: the value, where it came from, and what it costs to get wrong.
 *
 * Four states are kept visibly apart, because collapsing any two of them is
 * how this page would start lying:
 *
 * * **Nobody has said** — on a shipped default, or on nothing at all.
 * * **Answered** — with who, when and how.
 * * **Edited here, not saved** — exists only in this browser.
 * * **Stale** — answered, but a while ago, and this is a Deployment value.
 */
export function SetupField({
  spec, entry, effective, outstanding, stale, edit, onEdit, onRevert, focused, focusRef,
}) {
  const answered = isAnswered(entry);
  const provenance = answered ? entry.provenance : 'default';
  const edited = edit !== undefined;
  const shown = edited ? edit : (effective ?? '');

  const classes = [
    'setup-field',
    focused ? 'focused' : '',
    edited ? 'edited' : '',
    outstanding ? 'outstanding' : '',
  ].filter(Boolean).join(' ');

  return (
    <div className={classes} id={`field-${spec.id}`} ref={focusRef}>
      <div className="setup-field-head">
        <label htmlFor={`input-${spec.id}`}>
          {spec.label}
          {spec.units ? <span className="units"> ({spec.units})</span> : null}
        </label>
        <Chip level={edited ? 'warn' : PROVENANCE_LEVELS[provenance]}>
          {edited ? 'Edited, not saved' : PROVENANCE_LABELS[provenance]}
        </Chip>
      </div>

      <div className="setup-field-input">
        {spec.choices.length > 0 ? (
          <select
            id={`input-${spec.id}`}
            value={String(shown)}
            onChange={(e) => onEdit(e.target.value)}
          >
            {spec.choices.map((choice) => (
              <option key={choice} value={choice}>{choice}</option>
            ))}
          </select>
        ) : (
          <input
            id={`input-${spec.id}`}
            type={typeof spec.default === 'number' ? 'number' : 'text'}
            step="any"
            value={String(shown)}
            onChange={(e) => onEdit(e.target.value)}
            placeholder={spec.has_default ? String(spec.default) : 'no default — must be set'}
          />
        )}
        {edited && (
          <button type="button" className="link" onClick={onRevert}>revert</button>
        )}
      </div>

      {/* The reason a value gets measured rather than guessed. */}
      <p className={spec.silently_corrupts ? 'setup-consequence corrupts' : 'setup-consequence'}>
        {spec.silently_corrupts && <strong>Wrong quietly: </strong>}
        {spec.consequence}
      </p>

      <div className="setup-field-foot">
        {answered && (
          <span className="hint">
            {PROVENANCE_LABELS[provenance]}
            {entry.set_by ? ` by ${entry.set_by}` : ''}
            {entry.set_utc_ms ? `, ${setDate(entry.set_utc_ms)}` : ''}
            {entry.note ? ` — ${entry.note}` : ''}
          </span>
        )}
        {!answered && !spec.has_default && (
          <span className="errline">
            There is no sensible default for this. Until somebody says, the
            feature that uses it does not work.
          </span>
        )}
        {!answered && spec.has_default && (
          <span className="warnline">
            Nobody has checked this. It is on the shipped default of{' '}
            <code>{String(spec.default)}</code>.
          </span>
        )}
        {stale && (
          <span className="warnline">
            Set {daysOld(stale.age_ms)} ({setDate(stale.set_utc_ms)}). Still
            the same beach?
          </span>
        )}
        {SUPPLIED_NOTES[spec.supplied] ? (
          <span className="hint">{SUPPLIED_NOTES[spec.supplied]}</span>
        ) : null}
        {EFFECT_NOTES[spec.takes_effect] ? (
          <span className="hint">
            {EFFECT_NOTES[spec.takes_effect]} Read by <code>{spec.applied_by}</code>.
          </span>
        ) : null}
      </div>
    </div>
  );
}

/**
 * What would be saved, and whether the vessel will take it.
 *
 * The gate's verdict is rendered here *before* anything is pressed, which is
 * the only thing this copy of the gate is for. The Jetson evaluates the same
 * conditions off the vessel's own report at dispatch, and that is what
 * actually refuses — a page left open on a laptop is the accident the
 * condition exists for, and a guard the page could satisfy by claiming to be
 * satisfied would not catch it.
 */
export function SetupSaveBar({
  dirty, edits, doc, gate, state, connection, onDiscard, onSaved,
}) {
  const [by, setBy] = useState('');
  const [note, setNote] = useState('');
  const sentRef = useRef(null);

  // The most recent save, whatever became of it. Read off the command store,
  // which is fed by the backend's own `command_result` — not from the fetch
  // having returned. A button whose outcome is invented locally is the
  // failure this GUI has already paid for three times.
  const lastSave = Object.values(state.commands)
    .filter((c) => c.name === 'save_setup')
    .sort((a, b) => (a.issued_utc_ms || 0) - (b.issued_utc_ms || 0))
    .pop();
  const pending = lastSave?.status === 'pending';

  useEffect(() => {
    if (!lastSave || lastSave.id !== sentRef.current) return;
    if (lastSave.status === 'confirmed') {
      sentRef.current = null;
      onSaved();
    }
  }, [lastSave, onSaved]);

  if (dirty.length === 0) {
    return (
      <div className="setup-savebar">
        {lastSave && lastSave.status !== 'pending' && (
          <p className={lastSave.status === 'failed' ? 'errline' : 'okline'}>
            {lastSave.status === 'failed' ? 'Not saved. ' : 'Saved. '}
            {lastSave.detail}
          </p>
        )}
        <p className="hint">Nothing has been changed on this page.</p>
      </div>
    );
  }

  const labels = new Map((doc.fields ?? []).map((spec) => [spec.id, spec.label]));
  const specs = new Map((doc.fields ?? []).map((spec) => [spec.id, spec]));

  // What the vessel will still not be using after the save. Grouped by the
  // action needed, in the words the Python chose, so the page and the
  // pre-flight say the same thing.
  const notYetInUse = dirty
    .map((id) => specs.get(id))
    .filter((spec) => spec && spec.takes_effect !== 'immediately');

  function save() {
    const fields = {};
    for (const id of dirty) {
      fields[id] = { value: edits[id], provenance: 'entered', note: '' };
    }
    const id = connection.command('save_setup', {
      fields,
      by: by.trim(),
      note: note.trim(),
      // The explicit confirmation, carried to the Jetson rather than kept
      // here. It is not the condition — the vessel checks that itself, off
      // its own report — it is the record that somebody meant this.
      confirmed: true,
    });
    sentRef.current = id;
  }

  return (
    <div className="setup-savebar">
      <p>
        <strong>
          {dirty.length === 1
            ? 'One value has been changed here and not saved:'
            : `${dirty.length} values have been changed here and not saved:`}
        </strong>
      </p>
      <ul>
        {dirty.map((id) => <li key={id}>{labels.get(id) ?? id}</li>)}
      </ul>

      {notYetInUse.length > 0 && (
        <p className="warnline">
          Saving writes the file. It does not put these in use:{' '}
          {[...new Set(notYetInUse.map((spec) => spec.applied_by))].join(', ')}{' '}
          {notYetInUse.length === 1 ? 'reads this' : 'read these'} on reload or
          at startup, and the page will say so once the file is written.
        </p>
      )}

      {/* Who, so the record is worth something. Not a login — this GUI has no
          accounts and should not pretend to; it is the name that goes in the
          trace beside what the boat was doing at the time. */}
      <div className="setup-attribution">
        <label htmlFor="setup-by">Your name</label>
        <input
          id="setup-by"
          value={by}
          onChange={(e) => setBy(e.target.value)}
          placeholder="goes in the change record"
        />
        <label htmlFor="setup-note">Note</label>
        <input
          id="setup-note"
          value={note}
          onChange={(e) => setNote(e.target.value)}
          placeholder="how it was arrived at, e.g. tape measure, bow up"
        />
      </div>

      {!gate.allowed ? (
        <p className="errline">
          <strong>{gate.reason}</strong> {gate.remedy}
        </p>
      ) : !state.connected ? (
        <p className="errline">
          Not connected to the vessel, so nothing can be saved to it. The
          edits above exist only in this browser.
        </p>
      ) : (
        <p className="hint">
          The vessel is disarmed and not recording, so it will accept a change.
        </p>
      )}

      {lastSave && lastSave.status === 'failed' && (
        <p className="errline"><strong>Not saved.</strong> {lastSave.detail}</p>
      )}

      <div className="button-row">
        <ConfirmButton
          label={dirty.length === 1 ? 'Save this value' : `Save these ${dirty.length} values`}
          prompt="Write this to the vessel?"
          pending={pending}
          disabled={!gate.allowed || !state.connected}
          onConfirm={save}
        />
        <button type="button" onClick={onDiscard}>Discard these edits</button>
      </div>
    </div>
  );
}
